enabled: false
debug: false
regions:
  # Radius around spawn to process, blocks. Larger values dramatically
  # increase generation time.
  worldRadius: 5000
  # Height-map sampling step in blocks. Lower values give more precise
  # regions but slow generation.
  sampleSpacing: 32
  slopeExtra: 2
  # Region size thresholds used when merging and splitting.
  minCells: 300
  maxCells: 1500
  # Maximum simultaneously sampled chunks. Set to 0 to use CPU x2.
  maxParallelSamples: 0  # 0 => use CPU x2
  # Timeout for asynchronous chunk loading, seconds
  chunkTimeout: 40

database:
  type: sqlite        # sqlite | mysql
  file: plugins/HeliStates/regions.db   # для SQLite
  mysql:
    connectionString: jdbc:mysql://user:pass@localhost:3306/helicraft

