enabled: false
debug: false
regions:
  worldRadius: 5000
  sampleSpacing: 8
  terrainWeight: 1.0
  biomeWeight: 0.4
  minCells: 30
  maxCells: 3000
  coastBuffer: 50
  chaikinIter: 3

database:
  type: sqlite        # sqlite | mysql
  file: plugins/HeliStates/regions.db   # для SQLite
  mysql:
    connectionString: jdbc:mysql://user:pass@localhost:3306/helicraft

