enabled: false
debug: false
regions:
  # Radius around spawn to process, blocks. Larger values dramatically
  # increase generation time.
  worldRadius: 5000
  # Height-map sampling step in blocks. Lower values give more precise
  # regions but slow generation.
  sampleSpacing: 8
  steepSlope: 10
  # Region size thresholds used when merging and splitting.
  minCells: 400
  maxCells: 3000
  # Chaikin smoothing iterations. More iterations produce smoother
  # polygons but require extra processing time.
  chaikinIter: 2
  # Maximum simultaneously sampled chunks. Set to 0 to use CPU x2.
  maxParallelSamples: 0  # 0 => use CPU x2
  similarBiomes:
    forest_family:
      - FOREST
      - BIRCH_FOREST
    jungle_family:
      - JUNGLE
      - SPARSE_JUNGLE

database:
  type: sqlite        # sqlite | mysql
  file: plugins/HeliStates/regions.db   # для SQLite
  mysql:
    connectionString: jdbc:mysql://user:pass@localhost:3306/helicraft

