name: HeliStates
version: '1.0-SNAPSHOT'
main: ru.helicraft.helistates.HeliStates
api-version: '1.21'
softdepend:
  - BlueMap
authors: [ ms0ur ]
website: https://helicraft.ru
commands:
  helistates:
    description: HeliStates management
    usage: /<command> generate
